schema_version = "1.0.0"
id = "requin_blue_theme"
version = "1.1.0"
name = "Requin Blue"
tagline = "This is a Blender theme with a major blue color"
maintainer = "Muhamad Wicaksono <hirvi.3d@gmail.com>"
type = "theme"
website = "https://github.com/MozzarellaARC/Blender_Theme_Requin_Blue"
tags = ["Dark", "Inspired By"]
blender_version_min = "3.6.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2018-2025 Muhamad Wicaksono",
]